Fix JsonValue typing for objects w/o properties
0cfg/0cfg-utils pull request #12
Opened 2021-09-05 20:16 UTC by IlyaFilippovCodesphere

Previous type only worked for objects with properties.
i.e. 'hello' was not considered a valid JasonValue.

# Def. of Done
- [ ] Changes described in changelog.md 📝 
- [ ] Automatic tests written 🧪
- [ ] Manually tested 🧪
- [ ] Good code style
- [ ] Necessary migrate instructions added to migrate.md 🚀
- [ ] No known issues

2021-09-06 06:18 UTC, romfrolov approved these changes

2021-09-06 08:47 UTC, jonas-zipprick requested changes
Changelog entry please

2021-09-06 10:46 UTC, jonas-zipprick commented
Proof that string, numbers and booleans are valid JSON:

![Screenshot from 2021-09-06 12-45-38](https://user-images.githubusercontent.com/8794519/132205756-5cc57a5a-9be0-409c-a5a5-67c2455482f7.png)

2021-09-07 11:23 UTC, jonas-zipprick approved these changes

2021-09-07 11:23 UTC, romfrolov approved these changes

2021-09-07 11:45 UTC, merged